name: Test Windy Screenshot

on:
  workflow_dispatch:  # Bisa dijalankan manual dari tab Actions

jobs:
  capture:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run screenshot test
        run: |
          python src/main.py

      - name: Upload screenshot as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windy-screenshot
          path: windy.png
